language: java
jdk:
  - openjdk8
branches:
  only:
    - master

#Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"



before_deploy:
  - zip -r studyAws-springboot2-webservice *
  - mkdir -p deploy
  - mv studyAws-springboot2-webservice.zip deploy/studyAws-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: studyaws-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: studyaws-springboot-build
    key: studyaws-springboot2-webservice.zip
    bundle_type: zip
    application: studyaws-springboot2-webservice
    deployment_group: studyaws-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

#CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - juanmon@naver.com